### ISSUE TITLE
login with admin 

### ISSUE THREAD

**Issue by itsandrehere** [jeremykenedy/laravel-users#17]
Swift_RfcComplianceException
Address in mailbox given [] does not comply with RFC 2822, 3.6.2.

Do you know how I can solve it?
thnx.

**Comment by jeremykenedy** [comment]
My first thought is the only section that does any kind of checking on the email is the Validator in the following lines:

https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L94

https://github.com/jeremykenedy/laravel-users/blob/master/src/App/Http/Controllers/UsersManagementController.php#L201

You can try and adjust the validation rules above, but if its higher level it would be an issue with the Laravel Validation class.

That uses the Laravel Validator rule for email: https://laravel.com/docs/5.6/validation#rule-email

I am confused by opened issue and this package because this package does not send email in any way.

Thanks,

Jeremy
