### ISSUE TITLE
Attempting to get working with laratrust

### ISSUE THREAD

**Issue by trevorclarke** [jeremykenedy/laravel-users#21]
Hi,

I'm trying to get this working on fresh laravel 5.6 install with https://github.com/santigarcor/laratrust

I've run: 
php artisan make:auth

composer require "santigarcor/laratrust:5.0.*"

php artisan vendor:publish --tag="laratrust"

php artisan laratrust:setup

composer require jeremykenedy/laravel-users

php artisan vendor:publish --tag=laravelusers

Copied Directory [\vendor\jeremykenedy\laravel-users\src\resources\views] To [\resources\views\vendor\laravelusers]
Copied Directory [\vendor\jeremykenedy\laravel-users\src\resources\lang] To [\resources\lang\vendor\laravelusers]
Publishing complete.

This has resulted in files being created e.g. resources\views\vendor\laravelusers\usersmanagement

php artisan migrate

----
contents of routes/web.php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
----

If you can point out where I've gone wrong that would be great.

No error messages

**Comment by jeremykenedy** [comment]
I would open an issue with that repo since the issue your having is with that package. It works on Laravel and I cannot duplicate the issue on a base installation of Laravel. That repo you linked to is an on version 5.2 and I have have not used that project.

From what I recall package auto-discovery was not part of Laravel on 5.2 and you will need to install the package and add it to the service provider array in app.php 

And as outlined in the [readme](https://github.com/jeremykenedy/laravel-users/blob/master/readme.md#installation-instructions) if you are using L5.2 you will need to use an older version of this

`composer require jeremykenedy/laravel-users:1.2.0`

Then follow step 2 for Laravel 5.4 and below.

I would also suggest installing a base instance of Laravel and using https://github.com/jeremykenedy/laravel-roles instead of Laratrust. Laravel-users is built to work with laravel-roles.

https://laravel.com/docs/5.2/packages
